#! /bin/sh

IPTABLES='sudo /sbin/iptables'


# enable internet access
$IPTABLES -A POSTROUTING -t nat -o eth0 -j MASQUERADE
sudo echo "1" > /proc/sys/net/ipv4/ip_forward

$IPTABLES -N internet -t mangle

$IPTABLES -t mangle -A PREROUTING -i wlan0 -j internet
$IPTABLES -t mangle -A internet -j MARK --set-mark 99

$IPTABLES -t nat -A PREROUTING -m mark --mark 99 -p tcp --dport 80 -j DNAT --to-destination 10.0.0.1

$IPTABLES -t filter -A FORWARD -m mark --mark 99 -j DROP

